name: GitHub Actions

# Controls when the workflow will run.
on:
  # Triggers the workflow on push or pull request
  # events but only for the master branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this workflow manually from the Actions tab.
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run
# sequentially or in parallel.
jobs:
  # This workflow contains a single job called "build".
  tests:
    name: Running Units Tests
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will
    # be executed as part of the job.
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE,
      # so the job can access it.
      - uses: actions/checkout@v2

      # Runs all the tests inside the "tests" directory.
      - name: Compile Tests
        run: cd tests && make
      - name: Run Tests
        run: cd tests && ./run_tests
